spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mogoyun?characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          mogo:
            client-id: iWrzDPx5cx09q6eAXWCkESF4ZEBNBh3XRXSEnHiy
            client-secret: TksQIeW74zYxpS0N3TegWtzwmUDGUNggjwQCosjJiysWxtCRO7
            client-name: mogo_login
            scope: email
            authorization-grant-type: authorization_code
            redirect-uri-template: http://192.168.49.71:8080/login/oauth2/code/mogo_login
            client-authentication-method: post
        provider:
          mogo:
            authorization-uri: http://home.mogo.com/oauth/authorize
            token-uri: http://home.mogo.com/oauth/token
            user-info-uri: http://home.mogo.com/oauth/api/info
            user-name-attribute: id
docker:
  host: unix:///var/run/docker.sock
  version: 1.38
  registryUrl: https://hub.docker.com/
  registryUsername: georgeliu
  registryPassword: windowsxp2014
  auth:
    username: georgeliu
    password: windowsxp2014
buildPack:
  path: buildpacks
gitlab:
  host: http://git.mogo.com
  token: M3865gwCzNcVWbkPfTrZ
git:
  localPath: /Users/georgeliu/workspace
  keyPath: keys/id_rsa
maven:
  home: /usr/local/Cellar/maven/3.5.4/libexec
zipkin:
  url: http://zipkin.mogo.com/zipkin