# Default values for Gradle projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# echo "$(minikube ip) lolling-gibbon.testdomian" | sudo tee -a /etc/hosts
replicaCount: 1
image:
  pullPolicy: Always
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 4567
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi
ingress:
  enabled: true
