server:
  port: 8080

spring:
  application:
    name: helloworld
  profiles:
    active: dev
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML